// ─────────────────────────────────────────────────────────────────
// Outlet Design & Floor Zones Settings Page
// Accessible from Settings → Outlet Design (/settings/outlet-design)
//
// Features:
//   - Manage floor categories / zones (Indoor, Outdoor, Other, etc.)
//   - Assign/reassign any table to any category (e.g. move 'ratnadeep' to 'other')
//   - Track real-time sales generated by indoor vs outdoor vs other tables
// ─────────────────────────────────────────────────────────────────

'use client';

import { useEffect, useState, useMemo } from 'react';
import Link from 'next/link';
import AppLayout from '@/components/layout/AppLayout';
import Modal from '@/components/ui/Modal';
import {
  tablesApi,
  tableCategoriesApi,
  outletSalesApi,
  Table,
  TableCategory,
  OutletSalesAnalyticsResponse,
} from '@/lib/pos-api';
import { formatCurrency } from '@/lib/utils';
import { toast } from '@/lib/toast';
import {
  ArrowLeft,
  Plus,
  Pencil,
  Trash2,
  RefreshCw,
  TrendingUp,
  LayoutGrid,
  Users,
  Utensils,
  ArrowRightLeft,
  Check,
  ChevronLeft,
  ChevronRight,
  Building,
  TreePine,
  Coffee,
  Store,
} from 'lucide-react';

const PRESET_ICONS = ['🏠', '🌳', '📦', '☕', '🪑', '🌿', '🍹', '🏢', '✨'];
const PRESET_COLORS = [
  '#3b82f6', // Blue
  '#10b981', // Emerald
  '#f59e0b', // Amber
  '#8b5cf6', // Violet
  '#ec4899', // Pink
  '#06b6d4', // Cyan
  '#f97316', // Orange
  '#64748b', // Slate
];

export default function OutletDesignPage() {
  const [tables, setTables] = useState<Table[]>([]);
  const [categories, setCategories] = useState<TableCategory[]>([]);
  const [analytics, setAnalytics] = useState<OutletSalesAnalyticsResponse | null>(null);
  const [selectedPeriod, setSelectedPeriod] = useState<'today' | 'this_week' | 'this_month' | 'quarter' | 'all'>('this_month');
  const [loading, setLoading] = useState(true);
  const [analyticsLoading, setAnalyticsLoading] = useState(false);

  // Moving table loading state
  const [movingTableId, setMovingTableId] = useState<string | null>(null);

  // Category modal states
  const [categoryModalOpen, setCategoryModalOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<TableCategory | null>(null);
  const [categoryForm, setCategoryForm] = useState({
    name: '',
    color: '#3b82f6',
    icon: '🏠',
    description: '',
    order: 1,
  });
  const [categorySaving, setCategorySaving] = useState(false);

  // Table modal states
  const [tableModalOpen, setTableModalOpen] = useState(false);
  const [editingTable, setEditingTable] = useState<Table | null>(null);
  const [tableForm, setTableForm] = useState({
    tableNumber: '',
    capacity: 4,
    category: 'Indoor',
  });
  const [tableSaving, setTableSaving] = useState(false);

  // Load all data
  const loadData = async () => {
    setLoading(true);
    try {
      const [tablesRes, catsRes] = await Promise.all([
        tablesApi.list(),
        tableCategoriesApi.list(),
      ]);
      setTables(tablesRes.data || []);
      setCategories(catsRes.data || []);
    } catch (err: any) {
      toast.error('Failed to load tables and categories');
    } finally {
      setLoading(false);
    }
  };

  // Load analytics separately for responsive period toggles
  const loadAnalytics = async (period: string) => {
    setAnalyticsLoading(true);
    try {
      const res = await outletSalesApi.getAnalytics({ period });
      setAnalytics(res.data);
    } catch (err: any) {
      console.error('Failed to load outlet sales analytics', err);
    } finally {
      setAnalyticsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  useEffect(() => {
    loadAnalytics(selectedPeriod);
  }, [selectedPeriod]);

  // Group tables by category
  const tablesByCategory = useMemo(() => {
    const map = new Map<string, Table[]>();

    // Initialize all known categories in defined order
    categories.forEach((cat) => {
      map.set(cat.name, []);
    });

    // Ensure 'Other' exists
    if (!map.has('Other')) {
      map.set('Other', []);
    }

    tables.forEach((t) => {
      const catName = t.category || 'Other';
      if (!map.has(catName)) {
        map.set(catName, []);
      }
      map.get(catName)!.push(t);
    });

    return map;
  }, [tables, categories]);

  // Quick reassign table to category (e.g. Move ratnadeep to Other)
  const handleQuickReassign = async (tableId: string, tableNumber: string, targetCategory: string) => {
    setMovingTableId(tableId);
    try {
      await tablesApi.reassignCategory(tableId, targetCategory);
      toast.success(`Table "${tableNumber}" moved to ${targetCategory}`);
      setTables((prev) =>
        prev.map((t) => (t._id === tableId ? { ...t, category: targetCategory } : t))
      );
      // Reload analytics to reflect reassignment
      loadAnalytics(selectedPeriod);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to move table');
    } finally {
      setMovingTableId(null);
    }
  };

  // Open Add Category Modal
  const openAddCategory = () => {
    setEditingCategory(null);
    setCategoryForm({
      name: '',
      color: PRESET_COLORS[0],
      icon: '🪑',
      description: '',
      order: categories.length + 1,
    });
    setCategoryModalOpen(true);
  };

  // Open Edit Category Modal
  const openEditCategory = (cat: TableCategory) => {
    setEditingCategory(cat);
    const catIdx = categories.findIndex((c) => c._id === cat._id);
    setCategoryForm({
      name: cat.name,
      color: cat.color || '#3b82f6',
      icon: cat.icon || '🪑',
      description: cat.description || '',
      order: typeof cat.order === 'number' && cat.order > 0 ? cat.order : (catIdx !== -1 ? catIdx + 1 : 1),
    });
    setCategoryModalOpen(true);
  };

  // Reorder floor sections (Move left / right)
  const handleReorderCategory = async (index: number, direction: 'left' | 'right') => {
    const targetIndex = direction === 'left' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= categories.length) return;

    const newCategories = [...categories];
    const temp = newCategories[index];
    newCategories[index] = newCategories[targetIndex];
    newCategories[targetIndex] = temp;

    // Optimistically update
    setCategories(newCategories);

    try {
      const categoryIds = newCategories.map((c) => c._id);
      const res = await tableCategoriesApi.reorder(categoryIds);
      if (res.data) {
        setCategories(res.data);
      }
      toast.success(`Floor section "${temp.name}" moved`);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to reorder sections');
      await loadData();
    }
  };

  // Save Category
  const handleSaveCategory = async () => {
    if (!categoryForm.name.trim()) {
      toast.error('Category name is required');
      return;
    }

    setCategorySaving(true);
    try {
      if (editingCategory) {
        await tableCategoriesApi.update(editingCategory._id, categoryForm);
        toast.success(`Category "${categoryForm.name}" updated`);
      } else {
        await tableCategoriesApi.create(categoryForm);
        toast.success(`Category "${categoryForm.name}" created`);
      }
      setCategoryModalOpen(false);
      await loadData();
      await loadAnalytics(selectedPeriod);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to save category');
    } finally {
      setCategorySaving(false);
    }
  };

  // Delete Category
  const handleDeleteCategory = async (cat: TableCategory) => {
    if (!confirm(`Are you sure you want to delete category "${cat.name}"? Tables in this category will be moved to "Other".`)) {
      return;
    }

    try {
      await tableCategoriesApi.delete(cat._id);
      toast.success(`Category "${cat.name}" deleted`);
      await loadData();
      await loadAnalytics(selectedPeriod);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to delete category');
    }
  };

  // Open Add Table Modal
  const openAddTable = () => {
    setEditingTable(null);
    setTableForm({
      tableNumber: '',
      capacity: 4,
      category: categories[0]?.name || 'Indoor',
    });
    setTableModalOpen(true);
  };

  // Open Edit Table Modal
  const openEditTable = (table: Table) => {
    setEditingTable(table);
    setTableForm({
      tableNumber: table.tableNumber,
      capacity: table.capacity || 4,
      category: table.category || 'Indoor',
    });
    setTableModalOpen(true);
  };

  // Save Table
  const handleSaveTable = async () => {
    if (!tableForm.tableNumber.trim()) {
      toast.error('Table number/name is required');
      return;
    }

    setTableSaving(true);
    try {
      if (editingTable) {
        await tablesApi.update(editingTable._id, tableForm);
        toast.success(`Table "${tableForm.tableNumber}" updated`);
      } else {
        await tablesApi.create(tableForm);
        toast.success(`Table "${tableForm.tableNumber}" created`);
      }
      setTableModalOpen(false);
      await loadData();
      await loadAnalytics(selectedPeriod);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to save table');
    } finally {
      setTableSaving(false);
    }
  };

  // Delete Table
  const handleDeleteTable = async (table: Table) => {
    if (table.status === 'occupied' || table.activeOrder) {
      toast.error('Cannot delete an occupied table with an active order');
      return;
    }
    if (!confirm(`Delete table "${table.tableNumber}"?`)) {
      return;
    }

    try {
      await tablesApi.delete(table._id);
      toast.success(`Table "${table.tableNumber}" deleted`);
      await loadData();
      await loadAnalytics(selectedPeriod);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to delete table');
    }
  };

  return (
    <AppLayout>
      <div className="max-w-6xl mx-auto space-y-6 pb-12">
        {/* Top Navigation Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <Link
              href="/settings"
              className="p-2 rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 text-gray-600 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
              title="Back to Settings"
            >
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div>
              <h1 className="text-xl sm:text-2xl font-black text-gray-900 dark:text-white flex items-center gap-2">
                <LayoutGrid className="w-6 h-6 text-brand-600" />
                <span>Outlet Design & Floor Zones</span>
              </h1>
              <p className="text-xs sm:text-sm text-gray-500 font-medium">
                Organize tables into categories (Indoor, Outdoor, Other) and track revenue per zone.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2.5">
            <button
              onClick={openAddCategory}
              className="btn-secondary text-xs sm:text-sm font-bold flex items-center gap-1.5 px-3.5 py-2"
            >
              <Plus className="w-4 h-4" />
              <span>New Category</span>
            </button>
            <button
              onClick={openAddTable}
              className="btn-primary text-xs sm:text-sm font-bold flex items-center gap-1.5 px-3.5 py-2 shadow-sm"
            >
              <Plus className="w-4 h-4" />
              <span>Add Table</span>
            </button>
          </div>
        </div>

        {/* ═══════════════════════════════════════════════════════════════ */}
        {/* SECTION 1: ZONE SALES PERFORMANCE (INDOOR VS OUTDOOR VS OTHER) */}
        {/* ═══════════════════════════════════════════════════════════════ */}
        <div className="card p-5 sm:p-6 space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-gray-100 dark:border-gray-800">
            <div>
              <h2 className="text-base font-black text-gray-900 dark:text-white flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-emerald-600" />
                <span>Sales by Outlet Zone</span>
              </h2>
              <p className="text-xs text-gray-500 font-medium">
                Compare sales generated by indoor dining vs outdoor patio vs other areas.
              </p>
            </div>

            {/* Time Period Filter */}
            <div className="flex items-center gap-1 bg-gray-100 dark:bg-gray-800 p-1 rounded-xl">
              {(
                [
                  { id: 'today', label: 'Today' },
                  { id: 'this_week', label: 'This Week' },
                  { id: 'this_month', label: 'This Month' },
                  { id: 'quarter', label: 'This Quarter' },
                  { id: 'all', label: 'All Time' },
                ] as const
              ).map((p) => (
                <button
                  key={p.id}
                  onClick={() => setSelectedPeriod(p.id)}
                  disabled={analyticsLoading}
                  className={`px-3 py-1 text-xs font-bold rounded-lg transition-all ${
                    selectedPeriod === p.id
                      ? 'bg-white dark:bg-gray-900 text-brand-600 dark:text-white shadow-xs'
                      : 'text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white'
                  }`}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>

          {/* Metrics Grid */}
          {analyticsLoading && !analytics ? (
            <div className="py-12 flex justify-center">
              <RefreshCw className="w-6 h-6 text-brand-500 animate-spin" />
            </div>
          ) : !analytics || analytics.categories.length === 0 ? (
            <div className="py-10 text-center text-gray-400 text-sm">
              No sales recorded for this period yet.
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5">
              {analytics.categories.map((cat) => (
                <div
                  key={cat.name}
                  className="p-4 rounded-2xl border border-gray-200 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-900/50 relative overflow-hidden flex flex-col justify-between"
                  style={{ borderTopWidth: '4px', borderTopColor: cat.color || '#3b82f6' }}
                >
                  <div>
                    <div className="flex items-center justify-between gap-2 mb-2">
                      <div className="flex items-center gap-2">
                        <span className="text-xl">{cat.icon || '🪑'}</span>
                        <span className="font-black text-sm text-gray-900 dark:text-white">
                          {cat.name}
                        </span>
                      </div>
                      <span
                        className="text-[10px] font-black uppercase px-2 py-0.5 rounded-full"
                        style={{
                          backgroundColor: `${cat.color || '#3b82f6'}20`,
                          color: cat.color || '#3b82f6',
                        }}
                      >
                        {cat.percentage}% of total
                      </span>
                    </div>

                    <div className="mt-2">
                      <div className="text-2xl font-black text-gray-900 dark:text-white">
                        {formatCurrency(cat.totalSales)}
                      </div>
                      <p className="text-xs text-gray-500 font-medium mt-0.5">
                        {cat.orderCount} {cat.orderCount === 1 ? 'order' : 'orders'} • {cat.tablesCount} tables
                      </p>
                    </div>
                  </div>

                  <div className="mt-4 pt-3 border-t border-gray-200/60 dark:border-gray-800 flex items-center justify-between text-xs">
                    <span className="text-gray-500">Avg Bill (AOV)</span>
                    <span className="font-bold text-gray-900 dark:text-white">
                      {formatCurrency(cat.avgOrderValue)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* ═══════════════════════════════════════════════════════════════ */}
        {/* SECTION 2: TABLE ALLOCATION & CATEGORY ASSIGNMENT */}
        {/* ═══════════════════════════════════════════════════════════════ */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-base font-black text-gray-900 dark:text-white">
                Floor Zones & Tables
              </h2>
              <p className="text-xs text-gray-500 font-medium">
                Use the <span className="font-bold text-gray-700 dark:text-gray-300">←</span> and <span className="font-bold text-gray-700 dark:text-gray-300">→</span> buttons to reorder how sections appear on the Tables screen. Change any table&apos;s dropdown to move it to a different zone.
              </p>
            </div>
            <span className="text-xs font-bold text-gray-500 bg-gray-100 dark:bg-gray-800 px-3 py-1 rounded-full">
              {tables.length} Total Tables
            </span>
          </div>

          {loading ? (
            <div className="py-20 flex justify-center">
              <RefreshCw className="w-8 h-8 text-brand-500 animate-spin" />
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 items-start">
              {Array.from(tablesByCategory.entries()).map(([categoryName, catTables]) => {
                const catMeta = categories.find((c) => c.name === categoryName);
                const color = catMeta?.color || '#3b82f6';
                const icon = catMeta?.icon || '🪑';
                const catIndex = categories.findIndex((c) => c.name === categoryName);
                const isFirst = catIndex <= 0;
                const isLast = catIndex === -1 || catIndex >= categories.length - 1;

                return (
                  <div
                    key={categoryName}
                    className="card p-4 space-y-3.5 border-t-4"
                    style={{ borderTopColor: color }}
                  >
                    {/* Category Header */}
                    <div className="flex items-center justify-between pb-2.5 border-b border-gray-100 dark:border-gray-800">
                      <div className="flex items-center gap-2">
                        <span className="text-lg">{icon}</span>
                        <div>
                          <h3 className="font-black text-sm text-gray-900 dark:text-white flex items-center gap-1.5">
                            <span>{categoryName}</span>
                            <span className="text-xs text-gray-400 font-normal">
                              ({catTables.length})
                            </span>
                          </h3>
                        </div>
                      </div>

                      <div className="flex items-center gap-1">
                        {catIndex !== -1 && (
                          <div className="flex items-center bg-gray-100 dark:bg-gray-800 rounded-lg p-0.5 mr-1 border border-gray-200/60 dark:border-gray-700/60">
                            <button
                              type="button"
                              onClick={() => handleReorderCategory(catIndex, 'left')}
                              disabled={isFirst}
                              className="p-1 rounded text-gray-500 hover:text-gray-900 dark:hover:text-white hover:bg-white dark:hover:bg-gray-700 disabled:opacity-20 transition-all cursor-pointer disabled:cursor-not-allowed"
                              title="Move section earlier (left) on Tables screen"
                            >
                              <ChevronLeft className="w-3.5 h-3.5" />
                            </button>
                            <span
                              className="text-[10px] font-bold text-gray-500 dark:text-gray-400 px-1 select-none"
                              title="Display Sequence on Tables screen"
                            >
                              #{catIndex + 1}
                            </span>
                            <button
                              type="button"
                              onClick={() => handleReorderCategory(catIndex, 'right')}
                              disabled={isLast}
                              className="p-1 rounded text-gray-500 hover:text-gray-900 dark:hover:text-white hover:bg-white dark:hover:bg-gray-700 disabled:opacity-20 transition-all cursor-pointer disabled:cursor-not-allowed"
                              title="Move section later (right) on Tables screen"
                            >
                              <ChevronRight className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        )}
                        {catMeta && (
                          <button
                            onClick={() => openEditCategory(catMeta)}
                            className="p-1 rounded text-gray-400 hover:text-blue-600 hover:bg-gray-100 dark:hover:bg-gray-800"
                            title="Edit category"
                          >
                            <Pencil className="w-3.5 h-3.5" />
                          </button>
                        )}
                        {catMeta && !['Indoor', 'Outdoor', 'Pick Up', 'Other'].includes(categoryName) && (
                          <button
                            onClick={() => handleDeleteCategory(catMeta)}
                            className="p-1 rounded text-gray-400 hover:text-red-600 hover:bg-gray-100 dark:hover:bg-gray-800"
                            title="Delete category"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        )}
                      </div>
                    </div>

                    {/* Tables in this category */}
                    {catTables.length === 0 ? (
                      <div className="py-8 text-center text-xs text-gray-400 border border-dashed border-gray-200 dark:border-gray-800 rounded-xl">
                        No tables assigned to {categoryName}.
                      </div>
                    ) : (
                      <div className="space-y-2 max-h-[60vh] overflow-y-auto pr-0.5">
                        {catTables.map((table) => {
                          const isOccupied = table.status === 'occupied' || !!table.activeOrder;
                          const isMoving = movingTableId === table._id;

                          return (
                            <div
                              key={table._id}
                              className={`p-3 rounded-xl border transition-all ${
                                isOccupied
                                  ? 'border-red-200 dark:border-red-900/60 bg-red-50/40 dark:bg-red-950/20'
                                  : 'border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 hover:border-gray-300 dark:hover:border-gray-700 shadow-2xs'
                              }`}
                            >
                              <div className="flex items-start justify-between gap-2">
                                <div>
                                  <div className="flex items-center gap-2">
                                    <span className="font-black text-sm text-gray-900 dark:text-white">
                                      Table {table.tableNumber}
                                    </span>
                                    <span className="text-[10px] text-gray-500 font-semibold bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">
                                      {table.capacity || 4} seats
                                    </span>
                                    {isOccupied ? (
                                      <span className="text-[9px] font-black uppercase px-1.5 py-0.5 rounded bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300">
                                        Occupied
                                      </span>
                                    ) : (
                                      <span className="text-[9px] font-black uppercase px-1.5 py-0.5 rounded bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">
                                        Available
                                      </span>
                                    )}
                                  </div>
                                </div>

                                <div className="flex items-center gap-1">
                                  <button
                                    type="button"
                                    onClick={() => openEditTable(table)}
                                    className="p-1 rounded text-gray-400 hover:text-blue-600 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                                    title="Edit table details"
                                  >
                                    <Pencil className="w-3.5 h-3.5" />
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => handleDeleteTable(table)}
                                    disabled={isOccupied}
                                    className="p-1 rounded text-gray-400 hover:text-red-600 hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-30 transition-colors"
                                    title={isOccupied ? 'Cannot delete occupied table' : 'Delete table'}
                                  >
                                    <Trash2 className="w-3.5 h-3.5" />
                                  </button>
                                </div>
                              </div>

                              {/* Quick Move Dropdown */}
                              <div className="mt-2.5 pt-2 border-t border-gray-100 dark:border-gray-800 flex items-center justify-between gap-2 text-xs">
                                <span className="text-gray-400 text-[11px] font-medium flex items-center gap-1">
                                  <ArrowRightLeft className="w-3 h-3 text-gray-400" />
                                  <span>Move to:</span>
                                </span>

                                <select
                                  value={table.category || 'Other'}
                                  disabled={isMoving}
                                  onChange={(e) =>
                                    handleQuickReassign(table._id, table.tableNumber, e.target.value)
                                  }
                                  className="text-xs font-bold py-1 px-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-800 dark:text-gray-200 hover:border-gray-400 cursor-pointer disabled:opacity-50"
                                >
                                  {categories.map((c) => (
                                    <option key={c.name} value={c.name}>
                                      {c.name}
                                    </option>
                                  ))}
                                  {!categories.some((c) => c.name === 'Other') && (
                                    <option value="Other">Other</option>
                                  )}
                                </select>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════════════ */}
      {/* MODAL: ADD / EDIT CATEGORY */}
      {/* ═══════════════════════════════════════════════════════════════ */}
      <Modal
        open={categoryModalOpen}
        onClose={() => setCategoryModalOpen(false)}
        title={editingCategory ? 'Edit Floor Category' : 'Create Floor Category'}
      >
        <div className="space-y-4">
          <div>
            <label className="label">Category / Zone Name *</label>
            <input
              type="text"
              value={categoryForm.name}
              onChange={(e) => setCategoryForm({ ...categoryForm, name: e.target.value })}
              placeholder="e.g. Indoor, Outdoor, Rooftop, Balcony, Other"
              className="input text-sm"
              autoFocus
            />
          </div>

          <div>
            <label className="label">Icon</label>
            <div className="flex flex-wrap gap-2 mb-2">
              {PRESET_ICONS.map((emoji) => (
                <button
                  key={emoji}
                  type="button"
                  onClick={() => setCategoryForm({ ...categoryForm, icon: emoji })}
                  className={`w-9 h-9 text-lg rounded-xl flex items-center justify-center border transition-all ${
                    categoryForm.icon === emoji
                      ? 'border-brand-500 bg-brand-50 dark:bg-brand-950/40 ring-2 ring-brand-500/20'
                      : 'border-gray-200 dark:border-gray-700 hover:bg-gray-50'
                  }`}
                >
                  {emoji}
                </button>
              ))}
            </div>
            <input
              type="text"
              value={categoryForm.icon}
              onChange={(e) => setCategoryForm({ ...categoryForm, icon: e.target.value })}
              placeholder="Custom emoji or icon"
              className="input text-sm w-32"
            />
          </div>

          <div>
            <label className="label">Color</label>
            <div className="flex flex-wrap gap-2 mb-2">
              {PRESET_COLORS.map((col) => (
                <button
                  key={col}
                  type="button"
                  onClick={() => setCategoryForm({ ...categoryForm, color: col })}
                  className={`w-8 h-8 rounded-full border-2 transition-all flex items-center justify-center ${
                    categoryForm.color === col ? 'border-gray-900 dark:border-white scale-110' : 'border-transparent'
                  }`}
                  style={{ backgroundColor: col }}
                >
                  {categoryForm.color === col && <Check className="w-4 h-4 text-white drop-shadow" />}
                </button>
              ))}
            </div>
            <input
              type="color"
              value={categoryForm.color}
              onChange={(e) => setCategoryForm({ ...categoryForm, color: e.target.value })}
              className="w-12 h-8 p-0 border-0 rounded cursor-pointer"
            />
          </div>

          <div>
            <label className="label">Display Sequence / Order</label>
            <input
              type="number"
              min="1"
              value={categoryForm.order}
              onChange={(e) => setCategoryForm({ ...categoryForm, order: Number(e.target.value) || 0 })}
              placeholder="e.g. 1, 2, 3..."
              className="input text-sm w-32"
            />
            <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-1">
              Determines the display tab order on the Tables screen (1 appears first, then 2, etc.)
            </p>
          </div>

          <div>
            <label className="label">Description (Optional)</label>
            <input
              type="text"
              value={categoryForm.description}
              onChange={(e) => setCategoryForm({ ...categoryForm, description: e.target.value })}
              placeholder="e.g. Garden tables with umbrellas"
              className="input text-sm"
            />
          </div>

          <div className="flex justify-end gap-2 pt-3 border-t border-gray-100 dark:border-gray-800">
            <button
              type="button"
              onClick={() => setCategoryModalOpen(false)}
              className="btn-secondary text-xs"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleSaveCategory}
              disabled={categorySaving}
              className="btn-primary text-xs flex items-center gap-1.5"
            >
              {categorySaving && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
              <span>{editingCategory ? 'Update Category' : 'Create Category'}</span>
            </button>
          </div>
        </div>
      </Modal>

      {/* ═══════════════════════════════════════════════════════════════ */}
      {/* MODAL: ADD / EDIT TABLE */}
      {/* ═══════════════════════════════════════════════════════════════ */}
      <Modal
        open={tableModalOpen}
        onClose={() => setTableModalOpen(false)}
        title={editingTable ? `Edit Table ${editingTable.tableNumber}` : 'Add New Table'}
      >
        <div className="space-y-4">
          <div>
            <label className="label">Table Number / Name *</label>
            <input
              type="text"
              value={tableForm.tableNumber}
              onChange={(e) => setTableForm({ ...tableForm, tableNumber: e.target.value })}
              placeholder="e.g. 1, 2, ratnadeep, patio-1"
              className="input text-sm"
              autoFocus
            />
          </div>

          <div>
            <label className="label">Seating Capacity</label>
            <input
              type="number"
              min="1"
              max="50"
              value={tableForm.capacity}
              onChange={(e) => setTableForm({ ...tableForm, capacity: Number(e.target.value) || 1 })}
              className="input text-sm"
            />
          </div>

          <div>
            <label className="label">Floor Category / Zone *</label>
            <select
              value={tableForm.category}
              onChange={(e) => setTableForm({ ...tableForm, category: e.target.value })}
              className="input text-sm cursor-pointer"
            >
              {categories.map((cat) => (
                <option key={cat.name} value={cat.name}>
                  {cat.icon || '🪑'} {cat.name}
                </option>
              ))}
              {!categories.some((c) => c.name === 'Other') && (
                <option value="Other">🪑 Other</option>
              )}
            </select>
          </div>

          <div className="flex justify-end gap-2 pt-3 border-t border-gray-100 dark:border-gray-800">
            <button
              type="button"
              onClick={() => setTableModalOpen(false)}
              className="btn-secondary text-xs"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleSaveTable}
              disabled={tableSaving}
              className="btn-primary text-xs flex items-center gap-1.5"
            >
              {tableSaving && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
              <span>{editingTable ? 'Update Table' : 'Create Table'}</span>
            </button>
          </div>
        </div>
      </Modal>
    </AppLayout>
  );
}
